# Project information
site_name: +++ this site is archived, please see https://rancher.github.io/elemental +++
site_url: https://rancher.github.io/os2

# Repository
repo_name: rancher/os2
repo_url: https://github.com/rancher/os2
edit_uri: https://github.com/rancher/os2/edit/master/docs/

theme:
  name: material
  #logo: 'assets/logo_horizontal_white.png'
  #favicon: 'assets/favicon.ico'
  palette:
    - scheme: default
      primary: grey
      toggle:
        icon: material/eye-outline
        name: Dark Mode
    - scheme: slate
      primary: grey
      toggle:
        icon: material/eye
        name: Light Mode
  icon:
    repo: fontawesome/brands/github

# Customization
extra:
  homepage: https://rancher.github.io/os2

#google_analytics:
plugins:
  - search
  - markdownextradata: {}
  - redirects:
      redirect_maps:
        'index.md': 'https://rancher.github.io/elemental'


markdown_extensions:
- codehilite
- admonition
- pymdownx.tabbed
- pymdownx.superfences
- toc:
    permalink: true

nav:
  - Overview:
    - architecture.md
    - clusters.md
  - Install/Upgrade:
    - installation.md
    - upgrade.md
    - customizing.md
    - dashboard.md
    - mcm.md
    - ami.md
  - Reference:
    - configuration.md
    - versions.md
  - operator.md
